# Generated by Django 5.1 on 2024-10-11 11:10

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('no', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=255)),
                ('department', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('role', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
# builtins.id