# Generated by Django 5.1 on 2024-10-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='no',
            new_name='sr_no',
        ),
    ]
